service: pwa.demo
provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, env:AWS_REGION, 'ap-southeast-1'}
  stage: ${opt:stage, env:AWS_STAGE, 'dev'}
plugins:
  - serverless-finch
custom:
  siteName: pwa.demo
  client:
    bucketName: ${self:custom.siteName}
    distributionFolder: public
resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.client.bucketName}
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: 404.html
    # specifying the policies to make sure all files inside the Bucket are avaialble
    WebAppS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:custom.client.bucketName}/*
